const FACTOR_LIBRARY = [
  {
    name: "insider_cluster_buying",
    description: "Tests whether repeated open-market insider purchases by multiple insiders precede excess returns.",
    sourceTypes: ["insider_transactions"],
    expectedHoldingPeriod: "3 to 12 months",
    requiredData: [
      "insider transaction date",
      "filing date",
      "insider role",
      "transaction value",
      "price history",
      "sector classification",
    ],
    benchmark: "SPY and sector ETF",
    knownBiases: ["look-ahead bias", "filing-date lag", "small sample size", "sector concentration"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "politician_trade_following",
    description: "Tests whether disclosed politician trades contain repeatable signal after disclosure delays and crowding.",
    sourceTypes: ["politician_disclosures", "x_social"],
    expectedHoldingPeriod: "1 to 6 months",
    requiredData: ["disclosure date", "transaction date", "ticker", "position direction", "price history", "liquidity"],
    benchmark: "SPY and QQQ",
    knownBiases: ["disclosure delay", "selection bias", "media attention bias", "crowding"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "unusual_options_flow",
    description: "Tests whether unusual options activity has predictive value after controlling for liquidity, spreads, and news.",
    sourceTypes: ["x_social", "options_flow"],
    expectedHoldingPeriod: "1 day to 4 weeks",
    requiredData: ["options volume", "open interest", "bid-ask spread", "underlying price history", "news timestamps"],
    benchmark: "underlying stock and SPY",
    knownBiases: ["survivorship bias", "stale alerts", "spread/slippage", "hidden multi-leg trades"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "earnings_revision_momentum",
    description: "Tests whether analyst estimate revisions and recommendation changes precede relative strength.",
    sourceTypes: ["fundamentals", "analyst_revisions"],
    expectedHoldingPeriod: "1 to 3 months",
    requiredData: ["estimate revisions", "recommendation trends", "earnings dates", "price history", "sector classification"],
    benchmark: "SPY, QQQ, and sector ETF",
    knownBiases: ["data availability timing", "analyst herding", "sector dependence", "earnings-date clustering"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "social_research_density",
    description: "Tests whether repeated high-quality social research mentions create a useful research-prior signal.",
    sourceTypes: ["x_social", "bookmarks", "monitored_accounts"],
    expectedHoldingPeriod: "research queue only until independently validated",
    requiredData: ["post timestamp", "source account", "ticker", "claim category", "source reliability", "price history"],
    benchmark: "SPY and equal-weight watchlist",
    knownBiases: ["pump-and-dump risk", "source quality drift", "duplicate narratives", "crowded trades"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "relative_strength",
    description: "Tests whether price momentum relative to market and sector benchmarks persists after risk controls.",
    sourceTypes: ["price_history"],
    expectedHoldingPeriod: "1 to 6 months",
    requiredData: ["daily prices", "sector ETF prices", "volume", "corporate actions"],
    benchmark: "SPY, QQQ, and sector ETF",
    knownBiases: ["regime dependence", "crash risk", "rebalance timing", "transaction costs"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "valuation_reset",
    description: "Tests whether quality companies after valuation compression outperform once fundamentals stabilize.",
    sourceTypes: ["fundamentals", "price_history"],
    expectedHoldingPeriod: "6 to 18 months",
    requiredData: ["valuation metrics", "growth metrics", "profitability", "price drawdown", "earnings history"],
    benchmark: "SPY and sector ETF",
    knownBiases: ["value traps", "stale fundamentals", "multiple-definition drift", "sector concentration"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "post_earnings_drift",
    description: "Tests whether earnings surprises continue to drift after the market's initial reaction.",
    sourceTypes: ["fundamentals", "earnings"],
    expectedHoldingPeriod: "2 weeks to 3 months",
    requiredData: ["earnings date", "reported surprise", "guidance", "price reaction", "volume"],
    benchmark: "SPY, QQQ, and sector ETF",
    knownBiases: ["look-ahead bias", "event timestamp precision", "confounding news", "sample size"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
  {
    name: "quality_value_momentum_combo",
    description: "Tests a transparent multi-factor blend of quality, valuation, and momentum after explicit risk controls.",
    sourceTypes: ["fundamentals", "price_history"],
    expectedHoldingPeriod: "3 to 12 months",
    requiredData: ["profitability", "balance sheet metrics", "valuation metrics", "relative strength", "sector classification"],
    benchmark: "SPY, QQQ, and equal-weight factor universe",
    knownBiases: ["factor crowding", "overfitting", "rebalance timing", "regime dependence"],
    validationStatus: "not_validated",
    paperTradingStatus: "research_only",
    canDirectlyTrade: false,
  },
];

function getFactorLibrary() {
  return FACTOR_LIBRARY.map((factor) => ({ ...factor, requiredData: [...factor.requiredData], knownBiases: [...factor.knownBiases] }));
}

function getFactorByName(name) {
  return getFactorLibrary().find((factor) => factor.name === name) || null;
}

module.exports = {
  FACTOR_LIBRARY,
  getFactorByName,
  getFactorLibrary,
};
